service:
  name: groups

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2

functions:
  app:
    handler: src/app/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
